### ISSUE TITLE
0.1.0 release

### ISSUE THREAD

**Issue by stephenturner** [signaturescience/pracpac#79]
- [x] pkgdown action 
- [x] r cmd check action
- [x] full check of all internal roxygen docs #81 
- [x] Use case / pipeline vignette (`use-cases`) #71 
- [x] Testing all functions on windows
- [x] README.Rmd + `devtoopls::build_readme()` #43 
- [x] bump version in DESCRIPTION to 0.1.0
- [x] make repo public (before merging to main, so pkgdown should trigger at merge)
- [x] merge to main
- [x] run urlchecker again (see comments)
- [x] `devtools::check_rhub()`
- [x] fill out cran comments
- [x] one last devtools::check() and make sure main is up to date
- [x] `devtools::release()`
- [x] when accepted, cut release on this repo
- [x] close this issue
- [x] ~profit~ (free as in speech *and* free as in beer 🚀 )

**Comment by stephenturner** [comment]
Only urlchecker complaint should be fine:

```
> urlchecker::url_check()
✖ Error: README.md:10:56 404: Not Found
status](https://www.r-pkg.org/badges/version/pracpac)](https://CRAN.R-project.org/package=pracpac)
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by vpnagraj** [comment]
@stephenturner this is off to CRAN 🥳 

will let you know as soon as i hear back ...

**Comment by vpnagraj** [comment]
https://cran.r-project.org/package=pracpac

🥳 🥳
